name: Pull Request Merged

on:
  pull_request:
    types:
      - closed

jobs:
  check-merged:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the pull request is merged
        id: check-merge
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
            echo "Head Branch: ${{ github.event.pull_request.head.ref }}"
          else
            echo "Pull Request is not merged."
          fi
